#!/usr/bin/env bash

# This script performs a restore of the webserver from Bitvise. The restore
# script depends upon /etc/cryptopp.conf for passwords and shared
# secrets.
#
# cryptopp.conf is not available in this GitHub because it holds passwords
# and shared secrets. You have to have a copy of it somewhere. It is one of
# those files that you should have an encrypted local copy somewhere, like
# on a local machine or in email.
#
# Also see https://github.com/weidai11/website/tree/master/systemd

# Systemd adds random paths at times. Take full control of PATH.
PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH

if [ ! -f /etc/cryptopp.conf ]; then
	echo "/etc/cryptopp.conf is missing. The conf file is"
	echo "is needed for passwords and shared secrets. You"
	echo "should manually copy cryptopp.conf to /etc."
	exit 1
fi

# Ensure conf file is properly protected
chown root:root /etc/cryptopp.conf
chmod u=r,go= /etc/cryptopp.conf

# Get passwords needed for this script
wiki_password=$(grep WIKI_PASSWORD /etc/cryptopp.conf | cut -f 2 -d '=')
gnupg_password=$(grep GNUPG_PASSWORD /etc/cryptopp.conf | cut -f 2 -d '=')
bitvise_password=$(grep BITVISE_PASSWORD /etc/cryptopp.conf | cut -f 2 -d '=')
bitvise_host=$(grep BITVISE_HOST /etc/cryptopp.conf | cut -f 2 -d '=')

if [[ -z "${wiki_password}" ]]; then
    echo "WARNING: wiki_password is empty"
fi
if [[ -z "${gnupg_password}" ]]; then
    echo "WARNING: gnupg_password is empty"
fi
if [[ -z "${bitvise_password}" ]]; then
    echo "WARNING: bitvise_password is empty"
fi
if [[ -z "${bitvise_host}" ]]; then
    echo "WARNING: bitvise_host is empty"
fi

root_drive="/"

# This is the Bitvise restore.
if ! duplicity restore --file-to-restore ${root_drive} \
     "sftp://CryptoPPBackup:${bitvise_password}@${bitvise_host}:22480/cryptopp_com_backup" \
     "/tmp/restore" ;
then
    echo "Failed to restore VM from Bitvise"
    exit 1
fi

echo "Restore is complete. The restoration is available in /tmp/restore."

exit 0
